[package]
name = "slot"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6"
clap = { version = "4.2", features = ["derive"] }
eyre = "0.6"
serde_json = "1"
tokio = { version = "1.18.2", features = ["full", "sync"] }
webbrowser = "0.8"

[[bin]]
name = "slot"
path = "src/main.rs"
