[package]
name = "slot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
axum = "0.6"
clap = { version = "4.2", features = ["derive"] }
dirs = "5"
env_logger = "0.10"
graphql_client = "0.13.0"
log = "0.4"
reqwest = { version = "0.11.20", features = ["json"] }
serde = "1"
serde_json = "1"
tokio = { version = "1.18.2", features = ["full", "sync"] }
webbrowser = "0.8"

[[bin]]
name = "slot"
path = "src/main.rs"
